name: "Build the moon"
on:
  push:
    branches:
    - master
jobs:
  print-something:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build"
      run: |
        gcc main.c -o moon
        ./moon
    - name: "echo secrets"
      env:
        CONF_ENV: ${{ secrets.CONFIDENTIAL }}
      run: |
        echo "value of CONFIDENTIAL: ${CONF_ENV}"
